-- ZUCA Ops — МҮЗХ-ны бодит зуслангийн жагсаалт (73 зуслан).
-- Эх сурвалж: МҮЗХ «Хүүхдийн зуслангуудын дэлгэрэнгүй мэдээллийн жагсаалт» (2026.05.28) + zuca.mn (2026.09.16).
-- schema.sql → seed-zuca.sql → энэ файл гэсэн дарааллаар ажиллуулна. Дахин ажиллуулахад давхардахгүй.
-- Үүсгэсэн: python3 scripts/gen_seed.py > supabase/seed.sql

-- 0. Өмнөх хувилбарын зохиомол жишээ зуслангуудыг (хэрэв оруулсан бол) цэвэрлэнэ
delete from public.camps where name in ('Хөх тэнгэр хүүхдийн зуслан', 'Нарлаг хөндий', 'Оюуны гэрэл STEM зуслан', 'Хүрэлтогоот адал явдал', 'Бэлчээр эко зуслан', 'Туул голын эрэг', 'Алтан нуга', 'Хангайн өндөрлөг', 'Хөвсгөл далай зуслан', 'Дархан залуу судлаач', 'Орхон хөндийн зуслан', 'Говийн од', 'Бургастай', 'Эрдэнэт хүүхдийн ордон зуслан', 'Хэрлэн мөрөн', 'Цагаан сар зуслан', 'Ховдын оргил', 'Хар ус', 'Шинэ үе спорт зуслан', 'Сэлбэ урлагийн зуслан', 'Бөхөг уул', 'Сүүн далай', 'Их Монгол адал явдал', 'Жаргалантын нарс')
  and register_no is null and ownership is null and zuca_slug is null;

-- 1. zuca.mn дээрх 15 зуслан: seed-zuca.sql-ээр орсон бол МҮЗХ-ны талбаруудыг л нэмнэ
insert into public.camps (name, stage, season, aimag, soum, address, contact_person, phone, website, facebook, age_min, age_max, capacity, price_from, description, photos_count, ownership, register_no, founded_year, distance_km, notes, zuca_slug, position) values
  ('Шонхор хүүхдийн зуслан', 'active'::camp_stage, 'summer'::camp_season, 'Сэлэнгэ', 'Мандал сум', 'Түнхэл тосгон', null, '99039042, 94228885, 70150173', 'https://zuca.mn/camps/shonhor-camp', 'https://www.facebook.com/profile.php?id=61584089294116', 6, 18, null, null, null, 1, 'state', null, null, null, 'МҮЗХ жагсаалтад: «Шонхор»
МҮЗХ тайлбар: Сэлэнгэ аймаг цэргийн штаб-70362303, 70362171', 'shonhor-camp', 2000),
  ('Зулзагын гол зуслан', 'active'::camp_stage, 'summer'::camp_season, 'Дархан-Уул', 'Хонгор сум', '1-р баг, Дархан-Уул аймаг-аас 30 км', 'А.Амгалан', '80016066, 99270133', 'https://zuca.mn/camps/zulzagiin-gol-camp', null, 6, 18, 300, null, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/zulzagiin-gol-camp', 1, 'local', '9023143', 1974, 30.0, 'МҮЗХ жагсаалтад: «Зулзгын гол»
МҮЗХ тайлбар: Сувдмаа-99041026', 'zulzagiin-gol-camp', 12000),
  ('Урандөш хүүхдийн зуслан (Хөвсгөл)', 'active'::camp_stage, 'summer'::camp_season, 'Хөвсгөл', 'Бүрэнтогтох сум', 'Бүрэнтогтох сум, Мөрөн голын хөвөө «Их чигж», Мөрөн хотоос 18 км', 'Бямбадалай', '99223787, 99382215, 88107932', 'https://zuca.mn/camps/urandosh-camp', 'https://www.facebook.com/profile.php?id=61574198632756', 6, 18, 250, null, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/urandosh-camp', 6, 'local', '4126181', 1980, 18.0, 'МҮЗХ жагсаалтад: «Уран дөш, хөх сувд»
МҮЗХ тайлбар: Батчимэг-99240676', 'urandosh-camp', 18000),
  ('Цагаан нуга', 'active'::camp_stage, 'summer'::camp_season, 'Төв', 'Батсүмбэр сум', '3-р баг, Сөгнөгөрийн ам, Батсүмбэр-аас 20 км', 'Баясгалан', '99030511, 99688688', 'https://zuca.mn/camps/tsagaan-nuga-camp', 'https://www.facebook.com/tsagaannuga', 6, 18, 250, null, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/tsagaan-nuga-camp', 1, 'private', '1027719', 1959, 20.0, 'МҮЗХ тайлбар: Баясгалан 99030511, Оюунбилэг 99688688', 'tsagaan-nuga-camp', 40000),
  ('Мөрөөдөл олон улсын хүүхдийн зуслан', 'active'::camp_stage, 'summer'::camp_season, 'Төв', 'Батсүмбэр сум', '3-р баг, Баянгол ам, Батсүмбэр-аас 14 км', 'А.Цогтмагнай', '95191144, 77711144, 99909807', 'https://zuca.mn/camps/moroodol-camp', 'https://www.facebook.com/Dreamcamp.mn', 6, 18, 250, 100000, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/moroodol-camp', 5, 'private', '8133476', 2015, 14.0, 'МҮЗХ жагсаалтад: «Мөрөөдөл»', 'moroodol-camp', 41000),
  ('Номт хүүхдийн зуслан', 'active'::camp_stage, 'summer'::camp_season, 'Төв', 'Эрдэнэ сум', 'Баян давааны энгэр, эрдэнэ сум-аас 15 км', 'Батбаяр', '94025909, 85008989, 99101049', 'https://zuca.mn/camps/nomt-camp', 'https://www.facebook.com/Educare.Camp', 6, 18, 80, 85000, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/nomt-camp', 8, 'private', null, 2025, 15.0, 'МҮЗХ жагсаалтад: «Номт»
МҮЗХ тайлбар: вакум сургалтын төв', 'nomt-camp', 46000),
  ('English Camp', 'active'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Хан-Уул дүүрэг', 'Богд хаан уул дархан цаазат, Кувейтийн ам, Төв аймаг, кувейтийн ам-аас 28км', 'Түвшинбаяр', '99097476, 80248064', 'https://zuca.mn/camps/english-camp', 'https://www.facebook.com/profile.php?id=100063605438570', 6, 18, 250, 595000, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/english-camp', 10, 'private', '6178618', 2013, 28.0, 'МҮЗХ жагсаалтад: «Еnglish camp»
МҮЗХ тайлбар: Баярбилэг-86161668', 'english-camp', 49000),
  ('Галакси хүүхдийн зуслан', 'active'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Баянзүрх дүүрэг', 'Батмөнхийн ам, гацуурт-аас 18км', 'Н.Даваахүү', '99026644, 91916494', 'https://zuca.mn/camps/galaxy-camp', 'https://www.facebook.com/GALAXYZUSLAN', 6, 18, 200, 85000, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/galaxy-camp', 3, 'private', '9085211', 2008, 18.0, 'МҮЗХ жагсаалтад: «Галакси»
МҮЗХ тайлбар: Мягмарцэцэг-89048088', 'galaxy-camp', 54000),
  ('Сансар олон улсын хүүхдийн зуслан', 'active'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Баянзүрх дүүрэг', 'Баянзүрх дүүрэг, Гачууртын «Шар хоолойн ам», УБ-аас 38 км', 'Мөнхжаргал', '89038886, 89941805, 89108448', 'https://zuca.mn/camps/sansar-international-camp', 'https://www.facebook.com/profile.php?id=100067098795882', 6, 18, 650, null, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/sansar-international-camp', 1, 'private', '6894097', 1979, 18.0, 'МҮЗХ жагсаалтад: «Сансар»', 'sansar-international-camp', 55000),
  ('Нарс хүүхдийн зуслан (Pine camp)', 'active'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Сонгинохайрхан дүүрэг', 'Баян согоотын аманд, СХД-24 хороо-аас 5км', 'Н.Туяасайхан', '99096109, 11325329', 'https://zuca.mn/camps/nars-camp', 'https://www.facebook.com/narssummercamp', 6, 18, 280, 540000, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/nars-camp', 6, 'private', '8083614', 1972, 5.0, 'МҮЗХ жагсаалтад: «Нарс»
МҮЗХ тайлбар: Бямбажав-88907376', 'nars-camp', 56000),
  ('Нарлаг', 'active'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', 'Тэрэлж, Горхийн ам, Мэлхий хадны орчим, УБ-аас 65 км', 'Б.Буджаргал', '99104039, 86074039, 99115133', 'https://zuca.mn/camps/narlag-camp', 'https://www.facebook.com/share/1B1baTeoDY', 6, 18, 240, 85000, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/narlag-camp', 7, 'private', null, 1985, null, null, 'narlag-camp', 57000),
  ('Жавхлант зуслан', 'active'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', 'Тэрэлж, Мэлхий хадны ойролцоо', 'О. Буянхишиг', '95903070, 83040429', 'https://zuca.mn/camps/javkhlant-camp', 'https://www.facebook.com/javkhlantcamp', 6, 18, 240, null, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/javkhlant-camp', 1, 'private', '95333359', 1985, 15.0, 'МҮЗХ жагсаалтад: «Томүжин Зуны Зуслан / Жавхлант/»
МҮЗХ тайлбар: 2024, 2025 онуудад Жавхлант зусланг зуны 2 сар түрээсээр ажиллуулсан. 2026 онд зөвхөн 2 долоо хоногийн туршид буюу 2 ээлж зуслангаа хэрэгжүүлхээр төлөвлөж гадагшаа зарласан байгаа. Бусад үед Жавхлант зуслан Жавхлантаараа хэрэгжүүлнэ. О. Буянхишиг 95333359', 'javkhlant-camp', 58000),
  ('Би Монгол Хүн хүүхдийн хүрээ', 'active'::camp_stage, 'all_year'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', 'Горхи-Тэрэлж', null, '94221155, 91119923, 93139920', 'https://zuca.mn/camps/augaa-mongol-camp', 'https://www.facebook.com/BiMongolKhuncamp', 6, 18, 65, null, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/augaa-mongol-camp', 14, null, null, null, null, 'МҮЗХ жагсаалтад: «Би Монгол хүн” Хүүхдийн хүрээ»', 'augaa-mongol-camp', 68000),
  ('Дайманд хүүхдийн зуслан', 'active'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', null, 'Захирал', '88107245, 80123822, 99102615', 'https://zuca.mn/camps/diamond-zuslan', 'https://www.facebook.com/DiamondMind.Education', 7, 15, 60, null, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/diamond-zuslan', 2, 'private', null, 2024, 0.01, 'МҮЗХ тайлбар: Одоогоор зуслангын үйл ажиллагаа эхлээгүй байгаа. Барилга байгууламж дээрээ явж байгаа. Холбогдох дугаар: Доржханд-80123822 Зуслан хариуцсан менежер', 'diamond-zuslan', 72000),
  ('Joyful Family Camp', 'active'::camp_stage, 'summer'::camp_season, 'Төв', 'Цонжин болдог', 'Хөшөөний зүүн талд', 'Захирал', '94006296, 88776296', 'https://zuca.mn/camps/joyful-family-camp', 'https://www.facebook.com/profile.php?id=61589724478496', 6, 18, null, null, 'zuca.mn профайл дээр танилцуулга байгаа: https://zuca.mn/camps/joyful-family-camp', 9, null, '7030433', null, null, 'МҮЗХ жагсаалтад: «Joyful camp»', 'joyful-family-camp', 73000)
on conflict (zuca_slug) do update set
  ownership      = excluded.ownership,
  register_no    = excluded.register_no,
  founded_year   = coalesce(public.camps.founded_year, excluded.founded_year),
  distance_km    = coalesce(public.camps.distance_km, excluded.distance_km),
  capacity       = coalesce(public.camps.capacity, excluded.capacity),
  contact_person = coalesce(public.camps.contact_person, excluded.contact_person),
  soum           = coalesce(public.camps.soum, excluded.soum);

-- 2. Бусад 58 зуслан (ижил нэртэй байвал алгасна)
insert into public.camps (name, stage, season, aimag, soum, address, contact_person, phone, website, facebook, age_min, age_max, capacity, price_from, description, photos_count, ownership, register_no, founded_year, distance_km, notes, position)
select v.name::text, v.stage::camp_stage, v.season::camp_season, v.aimag::text, v.soum::text, v.address::text, v.contact_person::text, v.phone::text, v.website::text, v.facebook::text, v.age_min::int, v.age_max::int, v.capacity::int, v.price_from::int, v.description::text, v.photos_count::int, v.ownership::text, v.register_no::text, v.founded_year::int, v.distance_km::double precision, v.notes::text, v.position from (values
  ('ОУХНЦ', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Сонгинохайрхан дүүрэг', '34-р хороо, Баянголын ам, СХД-34 хороо-аас 10км', 'Отгонбат', '88110707', null, null, null, null, 300, null, null, 0, 'state', '9091858', 1978, 10.0, 'МҮЗХ тайлбар: Нарангэрэл-99915555', 1000),
  ('Оч', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', null, 'Гурван давааны ам нарстайн ам', null, null, null, null, null, null, null, null, null, 0, 'state', null, null, null, null, 3000),
  ('Дөл', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', null, 'Гурван давааны ам нарстайн ам', null, null, null, null, null, null, null, null, null, 0, 'state', null, null, null, null, 4000),
  ('Найрамдалын эрдэнэс', 'lead'::camp_stage, 'summer'::camp_season, 'Булган', 'Хангал сум', 'Хялгант хороо, Эрдэнэт хот-аас 30км', 'Жаргалсайхан', '99351548', null, null, null, null, 500, null, null, 0, 'state', '2074192', 1981, 30.0, 'МҮЗХ тайлбар: Буянжаргал-99361149', 5000),
  ('Бүтэн өнчин хүүхдийн Энэрэл', 'lead'::camp_stage, 'summer'::camp_season, 'Булган', 'Хангал сум', 'Дэлэнгийн ам, Эрдэнэт хот-аас 25 км', 'М.Майцэцэг', '99350559', null, null, null, null, 60, null, null, 0, 'state', '2074192', 1994, 25.0, 'МҮЗХ тайлбар: Оюунчимэг-99352571', 6000),
  ('Тамир', 'lead'::camp_stage, 'summer'::camp_season, 'Архангай', 'Батцэнгэл сум', 'Ар хэц, Эрдэнэ булган сумын 6- р баг-аас 7 км', 'Уранцэцэг', '99339590', null, null, null, null, 200, null, null, 0, 'local', '3031926', 1952, 7.0, 'МҮЗХ тайлбар: Балдандорж-80101315', 7000),
  ('Өвгөнжаргалант', 'lead'::camp_stage, 'summer'::camp_season, 'Баянхонгор', 'Эрдэнэцогт сум', '3-р баг', null, '88299266', null, null, null, null, 440, null, null, 0, 'local', null, 1965, null, 'МҮЗХ тайлбар: Ичинноров-86763247', 8000),
  ('Жаргалант', 'lead'::camp_stage, 'summer'::camp_season, 'Булган', null, null, null, null, null, null, null, null, null, null, null, 0, 'local', null, null, null, 'МҮЗХ тайлбар: Базаргүр-80633199', 9000),
  ('Андууд', 'lead'::camp_stage, 'summer'::camp_season, 'Говь-Алтай', 'Дэлгэр сум', 'Гуулин тосгон баг', null, '99940016, 89990016', null, null, null, null, null, null, null, 0, 'local', null, null, null, 'МҮЗХ тайлбар: Баярцэцэг-89012448', 10000),
  ('Бүрдийн Уянга', 'lead'::camp_stage, 'summer'::camp_season, 'Дундговь', 'Адаацаг сум', 'Сүм баг, Сүм хөх бүрдийн нутаг', 'Ганзориг', '80116922', null, null, null, null, null, null, null, 0, 'local', null, null, null, 'МҮЗХ тайлбар: Галсан-83014333', 11000),
  ('Жаргалан', 'lead'::camp_stage, 'summer'::camp_season, 'Дорноговь', 'Сайншанд', '2-р баг, Иргэдийн цэцэрлэгт хүрээлэн, Сайншанд сум-аас 22км', null, '90097052', null, null, null, null, 100, null, null, 0, 'local', '9025804', 2022, 22.0, 'МҮЗХ тайлбар: Баттайван-90097052', 13000),
  ('Баянбулаг', 'lead'::camp_stage, 'summer'::camp_season, 'Ховд', 'Ховд сум', 'Баянбулаг баг', 'Түнжээ', '99433070', null, null, null, null, null, null, null, 0, 'local', null, null, null, 'МҮЗХ тайлбар: Аймгийн ХГБХХГазраас нэвт рашаан сувилалын байрыг түшиглэн 290 хүүхдийг зөслөнгийн хөгжлийн үйлчилгээнд хамруулсан.Саранчимэг-99553463', 14000),
  ('Янзага', 'lead'::camp_stage, 'summer'::camp_season, 'Булган', 'Хангал сум', '3-р баг, Буурлын ар, хянгант сум-аас 10км', 'Батжаргал', '99366184', null, null, null, null, 130, null, null, 0, 'local', '940684', 1975, 10.0, 'МҮЗХ тайлбар: Баянзул-99179507', 15000),
  ('Тэмүүлэл', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Багануур дүүрэг', '1 хороо, Нарийны ам, Багануур дүүрэг-аас 17 км', 'Уранцоож', '88050912', null, null, null, null, 50, null, null, 0, 'local', '4551702', 2010, 17.0, 'МҮЗХ тайлбар: хөрөнгө оруулалтын ажил хийгдэж байгаа', 16000),
  ('Буянт хотхон', 'lead'::camp_stage, 'summer'::camp_season, 'Өмнөговь', 'Даланзадгад сум', '3-р баг, Даланзадгад сум-аас 43 км', 'Шинэхүү', '89038538', null, null, null, null, 150, null, null, 0, 'local', '3612657', 1954, 43.0, 'МҮЗХ тайлбар: Соёлчимэг-86116649', 17000),
  ('Баянгол зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', 'Горхи тэрэлж, 64 гарам, Налайх 6-р хороо-аас 6км', 'Өрнөхбилэг', '99463335', null, null, null, null, 150, null, null, 0, 'local', '5755069', 2014, 6.0, 'МҮЗХ тайлбар: Ууганцэцэг-96167612', 19000),
  ('Нью Дарьганга хүүхдийн зуслан', 'inactive'::camp_stage, 'summer'::camp_season, 'Сүхбаатар', 'Дарьганга сум', '4-р баг, Дарьганга сум-аас 3 км', 'Даваазагд', '91112108', null, null, null, null, 150, null, null, 0, 'local', null, 1940, 3.0, 'Идэвхгүй: Барилга нураасан, суурь л байгаа
МҮЗХ тайлбар: нураасан суурь байгаа', 20000),
  ('Өмнөговь хөдөлмөр зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Өмнөговь', 'Булган сум', 'Рашаант баг, Даланзадгад сум-аас 80км', 'Соёлчимэг', '86116649', null, null, null, null, 25, null, null, 0, 'labor', '9049797', 2019, 80.0, 'МҮЗХ тайлбар: Монгол гэрт -8 үйл ажиллагаа явуулдаг', 21000),
  ('Хот айл зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Говь-Алтай', '17 суманд байрласан', 'бүсчилсэн байдлаар, Алтай сум-аас 80км', 'Баярцэцэг', '89012448', null, null, null, null, 10, null, null, 0, 'labor', null, 2020, 80.0, 'МҮЗХ тайлбар: монгол гэрт -5 үйл ажиллагаа явуулдаг', 22000),
  ('Баянчандмань сум хөдөлмөр зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Баянчандмань сум', '2-р баг, Сүжийн ам, Баянчандмань сум-аас 2 км', 'Захирал', '99675482', null, null, null, null, 50, null, null, 0, 'labor', null, 2022, 2.0, 'МҮЗХ тайлбар: Стандарт хангаагүй', 23000),
  ('Жаргалант хөдөлмөр зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Жаргалант сум', '1-р баг, буурал, Жаргалан сум-аас 20 км', 'Батчимэг', '88893591', null, null, null, null, 50, null, null, 0, 'labor', null, 2022, 20.0, 'МҮЗХ тайлбар: Нарандулам-99982960', 24000),
  ('Орхон хөдөлмөр зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Өвөрхангай', 'Бат-Өлзийн сум', 'Улаан ам баг, Улаан ам баг-аас 30 км', 'Ууганчимэг', '99038210', null, null, null, null, 25, null, null, 0, 'labor', '9045678', 2024, 30.0, 'МҮЗХ тайлбар: бага сургуулийн байр,монгол гэр ашиглаж зуслан болгосон', 25000),
  ('Баялагхан хөдөлмөр зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Эрдэнэсант сум', 'угалзат баг, Эрдэнэ сант сум-аас 53 км', 'ЗДТГ дарга Сарантуяа', '96655605', null, null, null, null, 25, null, null, 0, 'labor', null, 2022, 53.0, 'МҮЗХ тайлбар: Стандарт хангаагүй', 26000),
  ('Баянзүрх хөдөлмөр зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Эрдэнэ сум', '5-р баг, эрэдэнэ сум-аас 10км', 'Даваасамбуу', '99894929', null, null, null, null, 60, null, null, 0, 'labor', '3892468', 2024, 10.0, 'МҮЗХ тайлбар: БЗД-нЗДТ газрын зуслан гэр-10, байшин-7', 27000),
  ('Хараацай', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Сүхбаатар дүүрэг', 'хандгайт ам, 19-хороо-аас 4км', 'Өлзийчимэг', '99088159', null, null, null, null, 150, null, null, 0, 'org', '9077529', 1982, 4.0, 'МҮЗХ тайлбар: Өнөр бүл хүүхдийн төвийн зуслан', 28000),
  ('Од', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Жаргалант сум', 'тал булаг, Монголын нууц товцоо амралт-аас 900м', 'Амгалан , Оюунбадрах', '91912348, 99839361', null, null, null, null, 80, null, null, 0, 'org', '9077316', 1990, 0.9, 'МҮЗХ тайлбар: Хүүхэд залуучуудын сургалт хүмүүжлийн тусгай цогцолборын дэргэд зуслан', 29000),
  ('Зост', 'lead'::camp_stage, 'summer'::camp_season, 'Баян-Өлгий', 'Сагсай сум', '2-р баг, хөлзет баг, Буянт сум-аас 15 км', 'Нурбек', '99424200', null, null, null, null, 120, null, null, 0, 'private', '3074536', 1986, 15.0, 'МҮЗХ тайлбар: Нурбек-99424200', 30000),
  ('Дөлгөөн Энх зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Дорнод', 'Баянтүмэн сум', '1-р баг, энхтолгой, Баянтүмэн сум-аас 16км', 'Б.Уянга', '88001005', null, null, null, null, 200, null, null, 0, 'private', null, 1981, 16.0, 'МҮЗХ тайлбар: Энх-Амгалан 9951021', 31000),
  ('Даян-Очир', 'lead'::camp_stage, 'summer'::camp_season, 'Завхан', 'Алдархаан сум', 'Богдынгол, Таван салааны ам, Улиастай сум-аас 45км', 'Амаржаргал', '99082180', null, null, null, null, 200, null, null, 0, 'private', '3501647', 1969, 45.0, 'МҮЗХ тайлбар: Цэвэлмаа-99012017', 32000),
  ('Гүн нуур', 'lead'::camp_stage, 'summer'::camp_season, 'Сэлэнгэ', 'Алтанбулаг сум', '3-р баг, Алтанбулаг сум-аас 16 км', 'Уранбилэг', '99086700', null, null, null, null, 150, null, null, 0, 'private', 'Ма64120302', 1979, 16.0, 'МҮЗХ тайлбар: Оюунжаргал-96979900', 33000),
  ('Цагаан-залаа', 'lead'::camp_stage, 'summer'::camp_season, 'Өвөрхангай', 'Хужирт сум', '2-р баг, Цагаан залаа газар, Хужирт сум-аас 30км', 'Энхмаа', '99624036', null, null, null, null, 100, null, null, 0, 'private', '2681145', 1964, 30.0, 'МҮЗХ тайлбар: үйл ажиллагаа тогтвортой биш Даваадулам-89946800', 34000),
  ('Сайхан хархираа', 'lead'::camp_stage, 'summer'::camp_season, 'Увс', 'Улаангом сум', '2-р баг, Улаангом сум-аас 28 км', 'Цолмонтуяа', '99015928', null, null, null, null, 130, null, null, 0, 'private', '4016084', 1953, 28.0, 'МҮЗХ тайлбар: Цолмонтуяа-99015928', 35000),
  ('Нүүдэлчдийн өв соёл', 'lead'::camp_stage, 'summer'::camp_season, 'Хэнтий', 'Мөрөн сум', null, null, null, null, null, null, null, null, null, null, 0, null, null, null, null, 'МҮЗХ тайлбар: цэнд-95606125', 36000),
  ('Монгол хүүхдийн гэр сургалт', 'lead'::camp_stage, 'summer'::camp_season, 'Хэнтий', 'Баян-Адарга сум', 'дууриалалт баг', 'Мөнхбат', '98224941', null, null, null, null, null, null, null, 0, null, null, null, null, null, 37000),
  ('Хэнтий хөдөлмөр зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Хэнтий', 'Баянхутаг сум', 'Сум суманд очиж, 50км', null, null, null, null, null, null, 20, null, null, 0, 'labor', null, 2014, 50.0, 'МҮЗХ тайлбар: цэнд-95606125', 38000),
  ('Хэрлэн зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Хэнтий', 'Мөрөн сум', '1-р баг, Чингис хот-аас 12 км', null, '99096662', null, null, null, null, 100, null, null, 0, 'private', '18220049', 1986, 12.0, 'МҮЗХ тайлбар: цэнд-95606125', 39000),
  ('Цоглог', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Батсүмбэр сум', 'Цогт өндөр 2 баг, 295 зөрлөг, Батсүмбэр-аас 18 км', 'Баттуяа', '88008870', null, null, null, null, 100, null, null, 0, 'private', '1027719', 2011, 18.0, 'МҮЗХ тайлбар: Нарандулам-99982960', 42000),
  ('Хайрын билэг', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Эрдэнэ сум', null, null, '99020596', null, null, null, null, null, null, null, 0, 'private', null, null, null, 'МҮЗХ тайлбар: Хүүхдийн нөхөн сэргээх сувилал', 43000),
  ('Скаут зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Батсүмбэр сум', 'Цогт өндөр 2 баг, Баянгол ам, Батсүмбэр-аас 12км', 'А.Билгүүн', null, null, null, null, null, 800, null, null, 0, 'private', null, 2010, 12.0, null, 44000),
  ('Оньс', 'inactive'::camp_stage, 'summer'::camp_season, 'Төв', 'Эрдэнэ сум', 'цонжин болдог, Эрдэнэ сум-аас 5.5 км', 'Баярцэцэг', '99103009', null, null, null, null, 36, null, null, 0, 'private', null, 2022, 5.5, 'Идэвхгүй: Газар, үл хөдлөх нь зарагдсан
МҮЗХ тайлбар: газар үл хөдлөх нь зарагдсан.', 45000),
  ('Нүүдэлчдийн соёл', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Эрдэнэ сум', null, 'Ариунцэнгэл', '95093503', null, null, null, null, 70, null, null, 0, 'private', null, 2022, null, null, 47000),
  ('Эко кемп', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Хан-Уул дүүрэг', null, null, null, null, null, null, null, 150, null, null, 0, 'private', null, null, null, null, 48000),
  ('Янзага', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Сүхбаатар дүүрэг', 'хандгайт ам, 19-р хороо-аас 8 км', 'Б.Энхмаа', '95507011', null, null, null, null, 150, null, null, 0, 'private', '9077987', 1987, 8.0, null, 50000),
  ('Сэлбэ', 'inactive'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Сүхбаатар дүүрэг', 'Бэлхийн ам, 20-р хороо-аас 26 км', null, null, null, null, null, null, 300, null, null, 0, 'private', null, 1942, 26.0, 'Идэвхгүй: 2017 оноос хойш үйл ажиллагаа явуулаагүй
МҮЗХ тайлбар: 2017 оноос хойш үйл ажиллагаа явуулаагүй', 51000),
  ('АВ gereen land', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Сүхбаатар дүүрэг', 'хандгайт ам, 19- хороо-аас хараацай зуслан 2 км', 'Мөнхзул', null, null, null, null, null, null, null, null, 0, 'private', null, 2025, 2.0, 'МҮЗХ тайлбар: барилгын ажил шинээр бүтээн байгуулалт хийгдэж байгаа', 52000),
  ('Маргаашийн хөгжил', 'inactive'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Сүхбаатар дүүрэг', 'Гүнжийн ам, 20 хороо-аас 13 км', null, '88117374', null, null, null, null, null, null, null, 0, 'private', null, 2021, 13.0, 'Идэвхгүй: 3 жил ажиллаагүй
МҮЗХ тайлбар: 3 жил ажиллаагүй', 53000),
  ('Өгөөмөр', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', null, 'Ганбаатар УИХурал гишүүн', null, null, null, null, null, null, null, null, 0, 'private', null, null, null, null, 59000),
  ('Анар', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', null, 'Арсланбат', null, null, null, null, null, null, null, null, 0, 'private', null, null, null, null, 60000),
  ('Нүүдэлчин зуслан', 'lead'::camp_stage, 'summer'::camp_season, 'Хэнтий', 'Өвөрхангай', null, 'Мөнхдэлгэр', '88937711', null, null, null, null, null, null, null, 0, 'private', null, null, null, 'МҮЗХ тайлбар: 4аймагт 4 ээлж зохион байгуулагдсан.', 61000),
  ('Ичигай', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', '55 км', null, null, null, null, null, null, null, null, null, 0, 'private', null, null, 55.0, null, 62000),
  ('Өгөөмөр заан', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Эрдэнэ сум', null, null, null, null, null, null, null, null, null, null, 0, 'private', null, null, null, null, 63000),
  ('Чухаг', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', null, 'Аргалант сум 76 км', 'Б.Мөнхбаяр', null, null, null, null, null, null, null, null, 0, 'private', null, null, null, null, 64000),
  ('Оньсхон', 'inactive'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', '60км', 'Т.Мөнх алдар', '99105988', null, null, null, null, null, null, null, 0, 'private', null, null, 60.0, 'Идэвхгүй: Сүүлийн 2 жил ажиллаагүй
МҮЗХ тайлбар: сүүлийн 2 жил ажиллаагүй', 65000),
  ('Тэрэлж boarding school', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', 'горхийн баруун салаа, орог ямаат, налайх-аас 20км', 'С.Цэндсайхан', null, null, null, null, null, 120, null, null, 0, 'private', '8265836', 2023, 20.0, 'МҮЗХ тайлбар: Тэрэлж boarding сургуулийн дотуур байрыг түшиглэн хэлний соёлын зуны сургалт явуулдаг.', 66000),
  ('Төгс нүүдэл', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', null, 'Цэнгэнбаяр', '99809006', null, null, null, null, 80, null, null, 0, 'private', null, 2011, null, 'МҮЗХ тайлбар: Шатрын сургалттай хүүхдийн зуслан', 67000),
  ('Цонжин cyber boarding', 'lead'::camp_stage, 'summer'::camp_season, 'Улаанбаатар', 'Налайх дүүрэг', null, null, '72826060', null, null, null, null, null, null, null, 0, null, null, null, null, 'МҮЗХ тайлбар: Ууганцэцэг-96167612', 69000),
  ('Ве', 'lead'::camp_stage, 'summer'::camp_season, 'Сэлэнгэ', 'Зүүнхараа', null, null, '90014005', null, null, null, null, null, null, null, 0, 'private', null, null, null, 'МҮЗХ тайлбар: Англи хэлтэй зуслан сургалтын үйл ажиллагаа', 70000),
  ('Найман шарга', 'lead'::camp_stage, 'summer'::camp_season, 'Төв', 'Мөнгөнморьт сум', 'байдлаг баг, Эрүүгийн олон, мөнгөн морьт сум-аас 18 км', 'Захирал', '99989487', null, null, null, null, 120, null, null, 0, 'labor', null, 2023, 18.0, 'МҮЗХ тайлбар: Стандарт хангаагүй', 71000)
) as v(name, stage, season, aimag, soum, address, contact_person, phone, website, facebook, age_min, age_max, capacity, price_from, description, photos_count, ownership, register_no, founded_year, distance_km, notes, position)
where not exists (select 1 from public.camps c where c.name = v.name);
